services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 5000:80
    depends_on:
      - app
    restart: unless-stopped

  app:
    build: .
    expose:
      - 5000
    volumes:
      # Cache di-persist di host agar tidak hilang saat container restart
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - API_BASE_URL=http://localhost:5000
      - FLASK_PORT=5000
    restart: unless-stopped
